version: "3.7"
services:
  app:
    build:
      args:
        user: bkrm
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: bkrm
    container_name: bkrm-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./uploaded_images:/var/www/storage/app/public/uploaded_images
      - ./merged:/var/www/storage/app/public/merged
    networks:
      - bkrm
  db:
    image: mariadb:10.9
    container_name: bkrm-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mariadb:/docker-entrypoint-initdb.d
      - ./bkrm_persist_data:/var/lib/mysql
    networks:
      - bkrm
  nginx:
    image: nginx:1.17-alpine
    container_name: bkrm-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
      - ./uploaded_images:/var/www/storage/app/public/uploaded_images
      - ./merged:/var/www/storage/app/public/merged
    networks:
      - bkrm
networks:
  bkrm:
    driver: bridge